### ISSUE TITLE
横長絵文字がWebUI上で正常に表示されない

### ISSUE THREAD

**Issue by yuicho** [yuicho-containers/yuichodon#2]
そもそも横長絵文字はMastodonの正式なフォーマットじゃないため。
ただ、表示されてくれた方が嬉しいので、横幅のリミットを外したい

**Comment by yuicho** [comment]
CSSの変更箇所
（ソースの場所はまだみてない）

```css
.reply-indicator__content .emojione, .status__content .emojione {
    /* width: 20px; */
    width: auto;
}

.detailed-status .status__content .emojione {
    /* width: 24px;*/
    width: auto;
}
```

**Comment by yuicho** [comment]
MastodonにはカスタムCSS機能があった…！
知らなかった……！

https://7-nana.github.io/2018/10/20/Mastodon-Custom-CSS/

**Comment by yuicho** [comment]
カスタムCSSに下記内容記載で解決（）
```css
.reply-indicator__content .emojione, .status__content .emojione {
    width: auto;
}

.detailed-status .status__content .emojione {
    width: auto;
}
```

<img width="362" alt="image" src="https://github.com/yuicho-containers/yuichodon/assets/43964607/5f7eed9e-f41e-443d-b98f-a03c39787a47">
